version: 2

jobs:
  build:
    machine: true
    parallelism: 2
    steps:
      - checkout
      - run: docker build 3.16-r13b -t mosesliao/cocos2dx-docker:3.16-r13b
      - run: docker build -t mosesliao/cocos2dx-docker .

  deploy:
    machine: true
    steps:
      - run:
          name: Run docker triggered build
          command: |
            curl -H "Content-Type: application/json" --data '{"docker_tag": "master"}' -X POST https://registry.hub.docker.com/u/mosesliao/cocos2dx-docker/trigger/67e3c6fa-3bc9-43eb-b7b3-dfd2a91ba919/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              except: master
      - deploy:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy
