version: 3

jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build 3.16-r13b -t mosesliao/cocos2dx:3.16-r13b
      - run: docker push mosesliao/cocos2dx:3.16-r13b
